### ISSUE TITLE
Array[String] no longer works with strings with commas

### ISSUE THREAD

**Issue by stanhu** [ruby-grape/grape#2013]
This passed in v1.1.0 but fails in v1.3.0: Reproduction step:

```diff
diff --git a/spec/grape/validations/validators/coerce_spec.rb b/spec/grape/validations/validators/coerce_spec.rb
index dbf57c9..c47f925 100644
--- a/spec/grape/validations/validators/coerce_spec.rb
+++ b/spec/grape/validations/validators/coerce_spec.rb
@@ -396,6 +396,19 @@ describe Grape::Validations::CoerceValidator do
         expect(JSON.parse(last_response.body)).to eq(%w[a b c d])
       end
 
+      it 'parses Array[String] type with strings with commas' do
+        subject.params do
+          requires :values, type: Array[String]
+        end
+        subject.get '/strings' do
+          params[:values]
+        end
+
+        get '/strings', values: 'a, b'
+        expect(last_response.status).to eq(200)
+        expect(JSON.parse(last_response.body)).to eq(['a, b'])
+      end
+
       it 'parses parameters with Array[Integer] type' do
         subject.params do
           requires :values, type: Array[Integer], coerce_with: ->(val) { val.split(/\s+/).map(&:to_i) }
```

```
Failures:

  1) Grape::Validations::CoerceValidator coerce using coerce_with parses Array[String] type with no coercion
     Failure/Error: expect(last_response.status).to eq(200)

       expected: 200
            got: 400

       (compared using ==)
     # ./spec/grape/validations/validators/coerce_spec.rb:408:in `block (4 levels) in <top (required)>'

Finished in 0.17659 seconds (files took 1.83 seconds to load)
47 examples, 1 failure

Failed examples:

rspec ./spec/grape/validations/validators/coerce_spec.rb:399 # Grape::Validations::CoerceValidator coerce using coerce_with parses Array[String] type with no coercion
```

**Comment by dblock** [comment]
Looks like a regression, but certainly a weird one. I would dig up what made it work in the first place and then we can decide whether we should fix it or not.

**Comment by stanhu** [comment]
I think it's a difference in  `Dry::Types::Coercions::Params.to_ary` vs `Virtus::Attribute`:

```ruby
(byebug) @coercer
#<Dry::Types[Constructor<Array fn=Dry::Types::Coercions::Params.to_ary>]>
(byebug) val
"tag1, tag2"
(byebug) @coercer[val]
*** Dry::Types::CoercionError Exception: "tag1, tag2" cannot be coerced to array
```

Relevant code: https://github.com/dry-rb/dry-types/blob/c39ea5cd751597368e2955b627feeeb2d8a23d65/lib/dry/types/coercions/params.rb#L134-L144 

I'm not quite sure what it's supposed to be doing here.

In Grape v1.1.0:

```ruby
[74, 83] in /Users/stanhu/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/virtus-1.0.5/lib/virtus/attribute/collection.rb
   74:         coerced = super
   75:
   76:         return coerced unless coerced.respond_to?(:each_with_object)
   77:
   78:         coerced.each_with_object(primitive.new) do |entry, collection|
=> 79:           collection << member_type.coerce(entry)
   80:         end
   81:       end
   82:
   83:       # @api private
(byebug) entry
"tag1, tag2"
(byebug) member_type
#<Virtus::Attribute type=Axiom::Types::String (String) options={:accessor=>:public, :strict=>false, :required=>true, :finalize=>true, :nullify_blank=>false, :coerce=>true, :reader=>:public, :writer=>:public, :default_value=>#<Virtus::Attribute::DefaultValue:0x00007fc2f1b74150 @value=nil>, :coercer=>#<Virtus::Attribute::Coercer:0x00007fc2f1b74060 @type=Axiom::Types::String (String), @primitive=String, @method=:to_string, @coercers=#<Coercible::Coercer:0x00007fc26180f3b0 @coercers={String=>#<Coercible::Coercer::String primitive=String>, Array=>#<Coercible::Coercer::Array primitive=Array>}, @config=#<Coercible::Configuration:0x00007fc2241d47a8 @string=#<Coercible::Configuration:0x00007fc2241de9b0 @boolean_map={"1"=>true, "on"=>true, "t"=>true, "true"=>true, "y"=>true, "yes"=>true, "0"=>false, "off"=>false, "f"=>false, "false"=>false, "n"=>false, "no"=>false}>, @integer=#<Coercible::Configuration:0x00007fc2241ddda8 @boolean_map={0=>false, 1=>true}, @datetime_format="%s", @datetime_proc=#<Proc:0x00007fc26180f4a0@/Users/stanhu/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/coercible-1.0.0/lib/coercible/coercer/integer.rb:26>>>>>}>
(byebug) member_type.coerce(entry)
"tag1, tag2"
```

**Comment by stanhu** [comment]
I guess the difference is that `Virtus::Attribute` does the coercing from `String` to `Array[String]` implicitly for us, but this needs to be defined explicitly with `coerce_from` with dry-types?

**Comment by dnesteryuk** [comment]
I am sorry but I don't think we need to fix it, it was a feature of Virtus which leaked to Grape. API should be strict, if `Array[String]` is defined as a type, users need to send array of strings :slightly_smiling_face: However, if a behavior of Virtus is required, a custom type or [coercer](https://github.com/ruby-grape/grape#custom-types-and-coercions) could be created. But, I wouldn't do that, I prefer explicit expectations without magic.

**Comment by stanhu** [comment]
Yeah, thanks, I'm still trying to figure out why in my application that adding an explicit `coerce_with` is still not working, but it does work in the test case.

**Comment by dblock** [comment]
Can we (maybe @stanhu?) please at the very least add t to UPGRADING retroactively?

**Comment by stanhu** [comment]
@dblock I'm one step ahead of you. https://github.com/ruby-grape/grape/pull/2016

I figured out why it wasn't working for me. I missed one use of `Array[String]`.

**Comment by dblock** [comment]
> @dblock I'm one step ahead of you. #2016

🚀
